# Auto-generated by 
if [[ -z "$WORKSPACE" ]]
then
  export WORKSPACE=/home/maouai233/edk2-vUDK2018
fi
if [[ -z "$EDK_TOOLS_PATH" ]]
then
  export EDK_TOOLS_PATH=/home/maouai233/edk2-vUDK2018/BaseTools
fi
if [[ -e /home/maouai233/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64 ]]
then
  if [[ ${PATH//home/maouai233/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64/} == $PATH ]]
  then
    export PATH=/home/maouai233/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
